$color = rgba(30, 32, 40, 1)
$inner_color = rgba(30, 32, 40, 0.66)
$outer_color = rgba(212, 92, 122, 1)
$font_color = rgba(247, 248, 250, 1)
$placeholder_color = rgba(247, 248, 250, 0.7)
$check_color = rgba(122, 143, 173, 1)
