background            #1e2028
foreground            #f7f8fa

# black
color0  #1e2028
color8  #8b909e

# red
color1  #b54a5a
color9  #b54a5a

# green
color2  #b54a5a
color10 #7a9e7e

# yellow
color3  #c9a96e
color11 #c9a96e

# blue
color4  #d45c7a
color12 #7a8fad

# magenta
color5  #d45c7a
color13 #d45c7a

#cyan
color6  #7a8fad
color14 #7a8fad

#white
color7  #e8e9ed
color15 #f7f8fa


